### ISSUE TITLE
Seleccion interfiere con el siguiente texto

### ISSUE THREAD

**Issue by ShulkMaster** [Misael-1998/BancoShell#4]
Cuando el usuario selecciona una opción esta se queda en pantalla y el siguiente texto que se imprima se pega al caracter seleccionado por ejemplo si el usuario presiona _**T**_
entonces el lo que queda en pantalla es:

`TSeleccione una de las opciones del menu o si desea salir presione la letra S`

con _**1**_

`1Ingresar clientes`

y asi sucesivamente con todas las letras, asi que el programa deberia de dejar un salto de linea para que no pase eso.

**Comment by ShulkMaster** [comment]
Mentiroso :,v

**Comment by Misael-1998** [comment]
Ahorita lo reviso
